name: linux-python

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  test:

    name: ${{ matrix.os }} py${{ matrix.case.python-version }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, ]  # Only Linux for _creation_]
        case:
          - python-version: 3.8

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
          persist-credentials: false

      - name: Fetch git tags
        run: git fetch origin 'refs/tags/*:refs/tags/*'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools_scm numpy pytest pytest-flake8

      - name: Create, install, lint and test
        run: |
          cd packages
          python create_python.py
          pip install python/. --use-feature=in-tree-build
          cd python
          pytest --flake8

  deploy:
    needs: test
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    # Only from the origin repository, not forks; only main and tags.
    if: github.repository_owner == 'emsig' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
          persist-credentials: false

      - name: Fetch git tags
        run: git fetch origin 'refs/tags/*:refs/tags/*'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools_scm numpy

      - name: Create package
        run: |
          cd packages
          python create_python.py

      - name: Replace naming scheme
        if: github.ref == 'refs/heads/main'
        run: |
          # Change setuptools-scm local_scheme to "no-local-version" so the
          # local part of the version isn't included, making the version string
          # compatible with Test PyPI.
          sed --in-place 's/"root"/"local_scheme":"no-local-version","root"/g' packages/python/setup.py
          cat packages/python/setup.py

      - name: Build source and wheel distributions
        run: |
          # Build source and wheel packages
          cd packages/python
          python setup.py sdist
          python setup.py bdist_wheel
          echo ""
          echo "Generated files:"
          ls -lh dist/

      - name: Publish to Test PyPI
        if: success()
        # [pin v1.4.2 (2021-02-08)]
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          packages_dir: packages/python/dist/
          repository_url: https://test.pypi.org/legacy/
          # Allow existing releases on test PyPI without errors.
          # NOT TO BE USED in PyPI!
          skip_existing: true

      - name: Publish to PyPI
        # Only for releases
        if: success() && github.event_name == 'release'
        # [pin v1.4.2 (2021-02-08)]
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          packages_dir: packages/python/dist/
