name: linux-python

# Only build PRs, the main branch, and releases.
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

# Use bash by default in all jobs
defaults:
  run:
    shell: bash

jobs:
  test:

    name: ${{ matrix.os }} py${{ matrix.case.python-version }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, ]  # Only Linux for _creation_]
        case:
          - python-version: 3.8

    steps:

      # Cancel any previous run of the test job; [pin v0.9.1 (2021-07-29)]
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b
        with:
          access_token: ${{ github.token }}

      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Need to fetch more than the last commit so that setuptools_scm can
          # create the correct version string. If the number of commits since
          # the last release is greater than this, the version still be wrong.
          # Increase if necessary.
          fetch-depth: 100
          # The GitHub token is preserved by default but this job doesn't need
          # to be able to push to GitHub.
          persist-credentials: false

      # Need the tags so that setuptools_scm can form a valid version number
      - name: Fetch git tags
        run: git fetch origin 'refs/tags/*:refs/tags/*'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools_scm numpy pytest pytest-flake8

      # Currently ONLY tests if it can be installed, plus linting
      - name: Flake8 with pytest
        run: |
          cd packages
          python create_python.py
          pip install python/. --use-feature=in-tree-build
          cd python
          pytest --flake8

  deploy:
    needs: test
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    # Only from the origin repository, not forks; only main and tags.
    if: github.repository_owner == 'emsig' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Need to fetch more than the last commit so that setuptools_scm can
          # create the correct version string. If the number of commits since
          # the last release is greater than this, the version will still be
          # wrong. Increase if necessary.
          fetch-depth: 100
          # The GitHub token is preserved by default but this job doesn't need
          # to be able to push to GitHub.
          persist-credentials: false

      # Need the tags so that setuptools_scm can form a valid version number
      - name: Fetch git tags
        run: git fetch origin 'refs/tags/*:refs/tags/*'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools_scm numpy

      - name: Create package
        run: |
          cd packages
          python create_python.py

      - name: Replace naming scheme
        if: github.ref == 'refs/heads/main'
        run: |
          # Change setuptools-scm local_scheme to "no-local-version" so the
          # local part of the version isn't included, making the version string
          # compatible with Test PyPI.
          sed --in-place 's/"root"/"local_scheme":"no-local-version","root"/g' packages/python/setup.py
          cat packages/python/setup.py

      - name: Build source and wheel distributions
        run: |
          # Build source and wheel packages
          cd packages/python
          python setup.py sdist
          python setup.py bdist_wheel
          echo ""
          echo "Generated files:"
          ls -lh dist/

      - name: Publish to Test PyPI
        if: success()
        # Hash corresponds to v1.4.1
        uses: pypa/gh-action-pypi-publish@54b39fb9371c0b3a6f9f14bb8a67394defc7a806
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          packages_dir: packages/python/dist/
          repository_url: https://test.pypi.org/legacy/
          # Allow existing releases on test PyPI without errors.
          # NOT TO BE USED in PyPI!
          skip_existing: true

      - name: Publish to PyPI
        # Only for releases
        if: success() && github.event_name == 'release'
        # Hash corresponds to v1.4.1
        uses: pypa/gh-action-pypi-publish@54b39fb9371c0b3a6f9f14bb8a67394defc7a806
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          packages_dir: packages/python/dist/
